### ISSUE TITLE
Предварительный интерфейс системы

### ISSUE THREAD

**Issue by Leerv474** [Leerv474/PeachNote#3]
![Untitled-2024-09-11-1053](https://github.com/user-attachments/assets/814b66c3-411a-4649-bcf7-8ab7af749042)

**Comment by wldmr-key** [comment]
что-то у меня картинка не открывается - вот ее можно аттачментом или ссылкой сделать

**Comment by Leerv474** [comment]
переотправил как png. Пока не дошел до Figma

**Comment by wldmr-key** [comment]
весьма мило. Сайт будет на английском?

**Comment by Leerv474** [comment]
пока думаю сделать выбор языка, это изображение накидал еще в начале лета и насчет языка совсем не подумал.
