### ISSUE TITLE
Предварительная схема данных

### ISSUE THREAD

**Issue by Leerv474** [Leerv474/PeachNote#4]
![ConceptualSchema](https://github.com/user-attachments/assets/f2038661-e2fd-4ca7-8645-c43c83457dcd)

**Comment by wldmr-key** [comment]
Достаточно странно твое разделение на концептуальную схему, Er-диаграмму и схему БД. Все картинки являются er-диаграммами. Первая - концептуальная схема данных, вторая - логическая, третья - как бы физическая

Подумай, нужна ли сущность таблицы. Не очень понятна идея привилегий пользователей в таблицах (нет в описании). Стоит ли условия выполнения делать атрибутом? Не нужен ли атрибут дата старта?

**Comment by Leerv474** [comment]
Таблицы нужны для группировки статус досок. К примеру, таблица Учеба, в которой различные статусы ожидание, текущее, сдано, защищено, выполнено, и таблица Курсовая, у которой свои статус-доски. 

Подумаю насчет привелегий, правда ли нужны мне они для простого предоставления просмотра чужих таблиц.

Условия выполнения - это скорее дополнительные сведения или описание задачи.

Аттрибут дата старта действительно нужен, о нем я задумался только после анализа аналогов.

**Comment by wldmr-key** [comment]
> Таблицы нужны для группировки статус досок. К примеру, таблица Учеба, в которой различные статусы ожидание, текущее, сдано, защищено, выполнено, и таблица Курсовая, у которой свои статус-доски.

правильно ли я понимаю, что "выполнено" в разных таблицах - это разное "выполнено"?

> Условия выполнения - это скорее дополнительные сведения или описание задачи.

стоп! Если это описание - то назови это описанием. Если это условие, то его невыполнение означает, что задача неактуальна. И, тогда, множественное число для названия атрибута по-прежнему неуместно

**Comment by Leerv474** [comment]
назову описание описанием, 

и доска "выполнено" разная для каждой таблицы, потому что наблюдать за выполнением учебных заданий удобнее отдельно от курсовой или домашних дел

**Comment by Leerv474** [comment]
Концептуальная схема
![ConceptualSchema drawio](https://github.com/user-attachments/assets/d4a8769d-9936-40c5-87d6-b3535d67d69c)
Логическая схема
![LogicalSchema](https://github.com/user-attachments/assets/312d2553-8a72-4fb7-b9d2-a7e97acc5844)
Физическая схема
![PhysicalSchema drawio](https://github.com/user-attachments/assets/07c022a2-ac84-4741-814f-7e6357299b1d)

**Comment by Leerv474** [comment]
Концептуальная схема
[documentation/dataSchemas/ConceptualSchema.drawio.svg](url)

**Comment by Leerv474** [comment]
Концептуальная схема
![ConceptualSchema](https://github.com/user-attachments/assets/11432257-d58f-40c1-a182-77c7863617a7)
Логическая схема
![LogicalSchema](https://github.com/user-attachments/assets/869ec161-e244-4dda-aa66-3f95cb3286eb)
Физическая схема
![PhysicalSchema](https://github.com/user-attachments/assets/9bc4ee87-578f-4229-91ca-51f508df358b)

**Comment by Leerv474** [comment]
Концептуальная
![ConceptualSchema](https://github.com/user-attachments/assets/d2bcd30b-5b66-4696-9249-9ba12257ead4)

Логическая
![LogicalSchema](https://github.com/user-attachments/assets/93f84c3a-8495-44b6-a749-7ae93b743144)

Физическая
![PhysicalSchema](https://github.com/user-attachments/assets/f75e192f-9974-4962-9595-4ceaeb2f1108)

**Comment by Leerv474** [comment]
Концептуальная
![ConceptualSchema](https://github.com/user-attachments/assets/221b81af-29fa-44d0-9240-d8b843186283)
Физическая
![PhysicalSchema](https://github.com/user-attachments/assets/db9b8424-6bb0-4446-8911-b59b89ffcf46)
Логическая
![LogicalSchema](https://github.com/user-attachments/assets/ec1a45c6-0afe-47f6-b3bf-3451e95a37e6)

**Comment by Leerv474** [comment]
Я сейчас задумываюсь, нужен ли id пользователю, если логин в любом случае должен быть уникальным

**Comment by wldmr-key** [comment]
> Я сейчас задумываюсь, нужен ли id пользователю, если логин в любом случае должен быть уникальным

два уникальных идентификатора точно не нужны

На логическую и физическую схемы пока не смотрю, хорошо? Их время еще не пришло...

Таблицы и доски - это синонимы? Зачем тебе путать читателя?
Номер стадии выполнения - нет в описании

Делиться информацией с другими пользователями передумал?

**Comment by Leerv474** [comment]
> На логическую и физическую схемы пока не смотрю, хорошо? Их время еще не пришло...

Понял

> Таблицы и доски - это синонимы? Зачем тебе путать читателя?

Нужно переименовать поля или таблицы? Можно было бы тогда статус-таблицу переименовать в статус-список, называть просто статусом точно собьет с толку.

Номер стадии выполнения я добавил в описание, но вместо стадии написал этапы, поправлю

Насчет дележки информацией я запутался, нужно ли мне вообще беспокоится о связи многие ко многим, если идентификатор автора доски - главное, что нужно при запросе. Если условно просто передавать ссылку другому пользователю на просмотр, то нужно ли это как-то фиксировать в базе данных или нет?

**Comment by wldmr-key** [comment]
В описании у тебя "таблицы". На схеме "доски"

Статус-таблицы - ладно уж, норм

`Насчет дележки информацией я запутался` - это к описанию требований к системе... В начале опиши, как хочется, а потом уже можно проектировать
