### ISSUE TITLE
Описание курсовой работы

### ISSUE THREAD

**Issue by Leerv474** [Leerv474/PeachNote#5]
# Приложение для составления заметок и расписания по системе "Getting Things Done"

Название: **PeachNote**

Цель: разработать и реализовать систему заметок на основе методологии "Getting Things Done", использование которой обеспечивает структурированное управление задачами человека или группы людей.

## Описание предметной области

Система заметок работает на основе методологии "Getting Things Done", которая разбивает задачи по сложности, важности и условиям выполнения. Элементы системы "Getting Things Done", разработанной Дэвидом Алленом, предусматривают несколько "куч" задач с различными характеристиками, описанными ниже:

1. Задачи — действия и цели пользователя.
2. Проекты — задачи, для выполнения которых требуется несколько шагов.
3. Контексты — условия, при которых эти задачи могут быть выполнены.
4. Справочные материалы.
5. Календарь.
6. Списки ожидания — задачи, выполнение которых зависит от внешних факторов.

### Описание методологии GTD

Применение методологии состоит из 4 шагов:  
Запись → Обработка → Пересмотр → Выполнение.

Обработка заключается в присвоении категории задачам по следующим вопросам:

1. Является ли это задачей?
2. Эта задача одношаговая?
3. Если это задача, зависит ли она от внешних факторов?
4. Эта задача неотложная?

Следуя этим вопросам, задачи распределяются по нескольким категориям:

1. Корзина — изначальный список задач.
2. Проекты — список проектов.
3. Отложенные задачи — задачи, не требующие немедленного выполнения.
4. Текущие задачи — задачи, выполнение которых началось.
5. Ожидание — задачи, зависящие от внешних факторов.
6. Выполненные задачи.

### Понятия системы

- _Система заметок GTD_ — система заметок на основе методологии "Getting Things Done", разработанной Дэвидом Алленом, предназначенная для структурированного контроля выполнения задач.
- _Пользователь_ — любое зарегистрированное лицо, которое пользуется данной системой.
  > Атрибуты: логин, пароль, номер телефона.
- _Задача_ — любая заметка, добавленная пользователем для дальнейшего распределения и выполнения.
  > Атрибуты: название, описание, срок, дата создания, дата выполнения, приоритет. Срок и описание условий выполнения — необязательные поля.
- _Проект_ — это задача, на выполнение которой требуется несколько шагов (подзадач).
  > Атрибуты: название, описание, срок. Срок и описание — необязательные поля.
- _Статус-таблица_ — это список, в который заносятся задачи и проекты в зависимости от статуса их выполнения.
  > Атрибуты: название, номер этапа выполнения.
- _Доска_ — это хранилище статус-таблиц, в рамках которого создаются задачи и проекты.
  > Атрибуты: название.

_Проекты_ состоят из _Задач_ (один ко многим).  
_Статус-таблицы_ состоят из _Задач_ и _Проектов_ (один ко многим).  
_Доски_ состоят из _Статус-таблиц_ (один ко многим).  
_Доски_ принадлежат _Пользователям_ (многие к одному).

### Функции системы

Функции:
- создание досок пользователя;
- создание дополнительных статус-таблиц;
- создание задач, проектов, статус-таблиц и досок;
- редактирование задач, проектов, статус-таблиц и досок;
- преобразование задач в проекты;
- изменение статуса задач и проектов;
- авторизация и регистрация пользователя;
- добавление доступа на просмотр досок.

Реализация функционала:

В досках по умолчанию присутствуют 5 статус-таблиц: Проекты, Отложенные задачи, Текущие задачи, Ожидание, Выполнено. При этом можно добавить дополнительные _статус-таблицы_ под нужды пользователя. Дополнительные _статус-таблицы_ воспринимаются как стадии выполнения задач и не могут служить изначальным статусом.
Отдельно от досок существует _Корзина_ - список выгруженных задач.

Созданные _задачи_ изначально попадают в _Корзину_. Присвоить _статус_ можно либо при создании, либо после. Присвоение _статуса_ осуществляется посредством вопросов и соответствующих кнопок согласно [Описанию методологии GTD](#описание-методологии-gtd):

```
|--> Является ли это задачей?
|  |--> ДА  -> следующий вопрос
|  |--> НЕТ -> Удалить?
|           |--> ДА
|           |--> НЕТ -> остается в корзине
|
|--> Эта задача одношаговая?
|  |--> ДА  -> следующий вопрос
|  |--> НЕТ -> преобразование в проект
|
|--> Эта задача полностью зависит от внешних факторов?
|  |--> ДА  -> задача попадает в доску ожидания
|  |--> НЕТ -> следующий вопрос
|
|--> Эта задача неотложная?
|  |--> ДА  -> задача попадает в текущие задачи
|  |--> НЕТ -> задача попадает в отложенные задачи
```

В окне распределения присутствуют кнопки выбора _статус-таблицы_ и  _доски_.

Проекты не могут находиться в _статус-таблицах_ Отложенные задачи, Текущие задачи и Ожидание. Следовательно, все пункты, содержащиеся в перечисленных досках, являются задачами.

Существуют расширенные виды статус-таблиц, задач и проектов, в которых отображается более подробная информация.

#### Функционал задач

Окно создания задачи содержит:
- редактирование атрибутов;
- кнопку создания в корзину;
- кнопку создания;
- кнопку распределения в зависимости от вида задачи (проектная или самостоятельная).

Расширенный вид задач содержит:
- функции редактирования атрибутов;
- кнопку удаления;
- кнопку преобразования в проект;
- кнопка перемещения на другую доску.

Перенос задач по статус-таблицам осуществляется нажатием кнопки (->) или перетягиванием курсором. Нажатие кнопки (->) имеет следующий функционал:
- Если задача находится в Корзине, начинается ее распределение.
- Если задача находится в Отложенных задачах, она либо попадает в Текущие задачи, либо преобразуется в Проект.
- Если задача находится в Ожидании, она попадает в Выполнено.
- Если задача находится в Текущих задачах, она попадает в Выполнено или пользовательский этап выполнения, если таковой был создан.

Приоритет задачи влияет на ее расположение в доске по вертикали. Если у задачи нет срока, приоритет остается статичным. В противном случае, приоритет будет расти с приближением срока. Например: изначально остается месяц — приоритет 1, остается 2 недели — приоритет 3, остается неделя — приоритет 5, остается день — приоритет 10. Рост приоритета происходит процентно в зависимости от времени до срока и начинается с изначального приоритета. Если приоритет поднялся до 10, задача подсвечивается, сигнализируя о приближающемся сроке.

Задачу можно в любой момент преобразовать в проект. Преобразование переносит условия в описание проекта, и появляется возможность создавать задачи, связанные с данным проектом.

#### Функционал проектов

Расширенный вид проектов содержит:
- список задач с отображением их статуса;
- функции редактирования атрибутов.

Проекты могут находиться только в двух статус-таблицах: _Проекты_ и _Выполнено_, так как их статус выполнения

 зависит от задач, из которых они состоят. Связанные задачи попадают в _Текущие задачи_. По мере их выполнения шкала выполнения проекта будет расти. Если все задачи, связанные с проектом, выполнены, они перестают отображаться в доске _Выполнено_, и вместо них в _Выполнено_ попадает сам проект. Если какая-либо задача проекта подсвечена, проект также подсвечивается.

#### Функционал статус-таблиц

Расширенный вид статус-таблиц содержит:
- список задач с отображением их приоритета и срока;
- функции редактирования атрибутов.

Для изменения порядка пользовательских статус-таблиц необходимо редактировать таблицу.

#### Функционал досок

Расширенный вид досок содержит:
- редактор дополнительных _статус-таблиц_;
- кнопку удаления доски;
- добавление пользователей для просмотра;
- функции редактирования атрибутов.

Функция поделиться просмотром:
Пользователи, не являющиеся владельцами доски, могут просматривать ее содержание без возможности редактирования.
В настройках доски присутсвует функция добавления пользователей на просмотр по _имени пользователя_.
У приглашенного пользователя, принявшего приглашение, гостевая доска появляется в общем списке досок.

Удаление доски:
Удаление требует потверждения действия посредством ввода названия доски в поле подтверждения.

#### Функционал пользователя

- функции редактирования атрибутов;
- Telegram-оповещения.

Поле _номер телефона_ не является обязательным, но в случае подтверждения Telegram-бот будет оповещать пользователя в личных сообщениях.

## Заключение

Таким образом, конечный продукт представляет собой систему заметок, в которой реализовано распределение задач по перечисленным критериям и отслеживание их выполнения.

**Comment by wldmr-key** [comment]
отлично! Правильно ли я понимаю, что пользователи сервиса не имеют связи друг с другом?

**Comment by Leerv474** [comment]
Если под связью вы имеете ввиду что-то вроде чата, то нет. Пользователей можно добавлять в просмотр таблиц. Это как бы приложение для отслеживания своих дел или проектов. Или для так условных тим лидов, которым отчитываются, что вот это сделано, и они себе помечают.

**Comment by wldmr-key** [comment]
прикинь функционал - возможность шарить свои задачи (не все, а допустим по тегу или группе) для всеобщего обозрения или для определенного круга (как в гугл-клендаре, например)

**Comment by Leerv474** [comment]
# Приложение для составления заметок и расписания по системе “Getting Things Done”

Название: **PeachNote**

Цель: разработать и реализовать систему заметок на основе метологии “Getting Things Done”, использование которой обеспечит струкое управление задачами человека или группы людей.

## Описание:

Система заметок будет работать на основе метологии “Getting Things Done”, которая разбивает задачи по сложности, важности и условиям выполнения. Элементы системы “Getting Things Done” разработанная Дэвидом Алееном предусматривает несколько “куч” задач отличающимися характеристиками описанными ранее, а именно:

1. Задачи - действия и цели пользователя.
2. Проекты - задачи, для выполнения которых требуется несколько шагов.
3. Контексты - т.е. условия, при которых эти задачи могут выполниться.
4. Справочные материалы.
5. Календарь.
6. Списки ожидания - задачи, выполнения которых зависит от внешних факторов.

### Описание метологии GTD

Применение метологии состоит из 4 шагов:
Запись → Обработка → Пересмотр → Выполнение.

Обрабока заключается в присуждении категории задачам по следующим вопросам:

1. Является ли это задачей?
2. Эта задача одношаговая?
3. Если это задача, зависит ли она от вшених факторов?
4. Эта задача неотложная?

Следуя этим вопросам задачи распределяются по нескольким категориям:

1. Корзина - изначальный список задач.
2. Проекты - список проектов.
3. Отложенные задачи - задачи, не требующие немедленного выполнения.
4. Текущие задачи - задачи, выполнение которых началось.
5. Ожидание - задачи, зависящие от внешних факторов.
6. Выполненные задачи.

## Реализация метлогии GTD в системе

### Описание объектов предметной области

- _Система заметок GTD_ - система заметок на основе метологии “Getting things done” разработанная Дэвидос Алленом, предназначенная для структурированного контроля выполнения задач.

- _Пользователь_ - любое зарегистрированное лицо, которое пользуется данной системой.
  > Атрибуты: логин, пароль, номер телефона.
- _Задача_ - любая заметка, добавленная пользователем, для дальнейшего распределения и выполнения.
  > Атрибуты: название, описание, срок, дата создания, дата выполнения, приоритет; срок и описание условий выполнения - необязательные поля.
- _Проект_ - это задача, на выполнение которой требуется несколько шагов (подзадач).
  > Атрибуты: название, описание, срок; срок и описание - необязательные поля.
- _Статус-таблица_ - это список, в который заносятся задачи и проекты в зависимости от статуса их выполнения.
  > Атрибуты: название, номер этапа выполнения.
- _Доска_ - это хранилице статус-таблиц, в рамках темы которого создаются задачи и проекты.
  > Атрибуты: название.

_Проекты_ состоят из _Задач_ (один из многих).
_Статус-таблицы_ состоят из _Задач_ и _Проектов_ (один из многих).
_Доски_ состоят из _Статус-таблиц_ (один из многих).
_Доски_ принадлежат _Пользователям_ (многие ко одному).

### Описание целостности данных

_Пользователь_

- логин: тип данных - varchar(128), должен быть уникальным и не пустым;
- пароль: тип данных - varchar(255), должен быть не пустым;
- номер телефона: тип данных - varchar(16).

_Задача_

- название: тип данных - varchar(128), не должен быть пустым;
- описание: тип данных - text;
- срок: тип данных - date;
- дата создания: тип данных - date, автоматически заполняется текущей датой при создании;
- дата выполнения тип данных - date, автоматически заполняется текущей датой при изменении статуса на выполнено;
- приоритет: тип данных - integer, больше нуля и не больше 100.

_Проект_

- название: тип данных - varchar(128), не должен быть пустым;
- описание: тип данных - text;
- срок: тип данных - date.

  > !ПРИМЕЧАНИЕ
  > Узнать дату конца или начала выполнения проекта можно через первую созданную или последную выполненную задачу, принадлежащую проекту.

_Статус-таблицы_

- название: тип данных - varchar(128), не должен быть пустым;
- номер этапа выполнения: тип данных - integer, больше нуля и не больше 20.

_Доска_

- название: тип данных - varchar(128), не должен быть пустым;

  > !ПРИМЕЧАНИЕ
  > Максимальное количество статус-таблиц в одной доске не превышает 20.

### Принцип работы

Функции:

- создание досок пользователя;
- создание дополнительных статус-таблиц;
- создание задач, проектов, статус-таблиц и досок;
- редактирование задач, проектов, статус-таблиц и досок;
- преобразование задач в проекты;
- изменение статуса задач и проектов;
- авторизация и регистрация пользователя;

Описание функционала:

В досках по-умолчанию присутвуют 6 статус-таблиц: корзина, проекты, отложенные задачи, текущие задачи, ожидание, выполнено. При этом возможно добавить дополнительные _статус-доски_ под нужды пользователя. Дополнительные _статус-таблицы_ воспринимаются в качестве стадий выполнения задач, они не могут служить изначальным статусом.
Созданные _задачи_ изначально попадают в _корзину_. Присвоить _статус_ возможно либо при создании, либо после создания.
Присваивание _статуса_ производится последством вопросов и соответсвующих кнопок согласно [Описанию метологии GTD](#описание-метологии-gtd):

```
|--> Является ли это задачей?
|  |--> ДА  -> следующий вопрос
|  |--> НЕТ -> Удалить?
|           |--> ДА
|           |--> НЕТ -> остается в корзине
|
|--> Эта задача одношаговая?
|  |--> ДА  -> следующий вопрос
|  |--> НЕТ -> преобразование в проект
|
|--> Эта задача полностью зависит от внешних факторов?
|  |--> ДА  -> задача попадает в доску ожидания
|  |--> НЕТ -> следующий вопрос
|
|--> Эта задача неотложная?
|  |--> ДА  -> задача попадает в текущие задачи
|  |--> НЕТ -> задача попадает в отложенные задачи
```
Проекты не могут находится в _статус-таблицах_ корзина, отложенные задачи, текущие задачи и ожидание. Следовательно, все пункты, содержащиеся в перечисленных досках являются задачами.

Существуют расширенные виды статус-таблицы, задач и проектов, в которых отображается более подробная информация.

#### Функционал задач

Окно создания задачи содержит:

- редактирование атрибутов;
- кнопка создания в корзину;
- кнопка создания;
- кнопка распределения в зависимости от вида задачи (проектная или самостоятельная).

Расширенный вид задач содержит:

- функции редактирования атрибутов;
- кнопка удаления;
- кнопка преобразования в проект.

Перенос задач по статус-таблицам производится посредством нажатия кнопки (->) или перетягивания ее курсором.
Нажатие кнопки (->) имеет следующий функционал:

- Если задача находится в Корзине, то начинается ее распределение.
- Если задача находится в Отложенных задачах, то она либо попадает в Текущие задачи, либо преобразуется в Проект.
- Если задача находится в Ожидание, то она попадает в Выполнено.
- Если задача находится в Текущих задачах, то она попадает в Выполнено или пользовательский этап выполнения, если таковой был создан.

От приоритета задачи зависит ее расположение в доске по вертикали. Если у задачи не присутствует срок, то ее приоритет остается статичным. В противном случае, ее приоритет будет расти с приближением срока. Например, изначально остается месяц - приоритет 1, остается 2 недели - приоритет 3, остается неделя приоритет 5, остается день - приоритет 10. Рост приоритета процентный согласно времени до срока и начинается с изначального приоритета. В случае, если приоритет поднялся до 10, задача подсвечивается, сигнализируя горящие сроки.

Задача в любой момент может быть преобразована в проект. Преобразование переносит условия в описание проекта. Появляется возможность создавать задачи, связанные с данным проектом.

#### Функционал проектов

Расширенный вид проектов содержит:

- список задач с отображением их статуса;
- функции редактирования атрибутов.

Проекты могут содержаться только в двух статус-таблицах: _Проекты_ и _Выполнено_, так как их статус выполнения проявляется в задачах, из который они состоят.
Свазанные задачи попадают в _Текущие задачи_. По мере их выполнения шкала выполнения проекта будет расти. Если все задачи связанные с проектом выполнены, то они перестаются отображаться в доске _Выполнено_ и вместо них в _Выполнено_ попадает сам проект. Если какая-либо задача проекта подсвечена, то проект также подсвечен.

#### Функционал статус-таблиц

Расширенный вид статус-таблиц содержит:

- список задач с отображением их приоритета и срока.
- функции редактирования атрибутов.

Для изменения порядка пользовательских статус-таблиц необходимо изменять таблицу.

#### Функционал досок

Расширенный вид досок содержит:

- редактор дополнительных _статус-таблиц_;
- кнопка удаления доски;
- добавление пользователей для просмотра;
- функции редактирования атрибутов.

#### Функционал пользователя

- функции редактирования атрибутов.
- Telegram оповещения

Поле _номер телефона_ не является обязательным, но в случае подтверждения Telegram бот будет оповещать пользователя в личные сообщения.


## Заключение

Таким образом, конечным продуктом является система заметок, в которую встроено распределение задач по перечисленным критериям и отслеживание выполнения этих задач.

**Comment by Leerv474** [comment]
Добавил описание целостности данных, поменял название сущности статус-доски на статус-таблицы и таблицы на доски

**Comment by wldmr-key** [comment]
это очень хорошее описание, но по стилю не ложится в канву курсовой работы. Предлагаю:

1) убрать будущее время
2) проверить опечатки
3) описание предметной области === описание методологии и основных понятий внутри нее (задача, проект, доска (?) и т.п.)
4) описание требований к системе === функции и понятия системы (пользователь, статус-таблицв и т.п.)
5) я бы приберег типизацию для логической или физической схемы

**Comment by Leerv474** [comment]
> 3. описание предметной области === описание методологии и основных понятий внутри нее (задача, проект, доска (?) и т.п.)
> 4. описание требований к системе === функции и понятия системы (пользователь, статус-таблицв и т.п.)

т.е. переименовать пункты?

> я бы приберег типизацию для логической или физической схемы

т.е. целостность данных и органичения целостности убрать из описания?

**Comment by wldmr-key** [comment]
ты все правильно понимаешь. 

Твой скорбный труд не пропадет
А перенесется в другое место

**Comment by Leerv474** [comment]
отредактировал и сохранил целостность в отдельно

**Comment by wldmr-key** [comment]
хорошо. Про шаринг задач передумал?

**Comment by Leerv474** [comment]
> Функционал досок
> Расширенный вид досок содержит:
> - редактор дополнительных
> - статус-таблиц;
> - кнопку удаления доски;
>  - **добавление пользователей для просмотра;**
> - функции редактирования атрибутов.


Нужно более подробно описать?

**Comment by wldmr-key** [comment]
не, норм. Шаринг, значит, для досок. ок
тут есть вопрос/проблема - где их увидит контрагент?

**Comment by Leerv474** [comment]
Это проблема моей фантазии. Я все не могу решить, просмотр будет просто через ссылку на просмотр или же сделать приглашение на просмотр, чтобы чужие доски были закреплены где-то в интерфейсе клиента и на них можно было бы всегда посмотреть.

**Comment by wldmr-key** [comment]
я бы предложил специальную доску - чужие задачи, куда все внешнее попадает (задачи, ведь, можно между досками таскать?)

а, может, и зря я к тебе пристаю с этим функционалом. Сам решай

**Comment by Leerv474** [comment]
> Функция поделиться просмотром:
Пользователи, не являющиеся владельцами доски, могут просматривать ее содержание без возможности редактирования.
В настройках доски присутсвует функция добавления пользователей на просмотр по _имени пользователя_.
У приглашенного пользователя, принявшего приглашение, гостевая доска появляется в общем списке досок.

Решил сделать так, но теперь встревает ваше предположение по перетаскиванию задач по доскам. Весь смысл приложения в том, что задачи изолируются друг от друга по доскам. Можно сделать так, что корзина одна, и во время распределения нужно выбрать, в какую доску перейдет задача. Таким образом, если появилось что-то важное, по типу забрать посылку из почты, человек просто создает задачу и оставляет ее в корзине, а потом только выбирает, что это вообще такое, учеба, работа, дом или личное. Если в случае с Таблицей выполнено все однозначно - у нас их должно быть несколько для конечного разграничения задач для мониторинков результатов, то с корзиной все сложнее, и не думаю, что есть большой смысл иметь несколько.
Но вот если пользователь перепутал доску, заставлять пересоздавать задачу? Наверное все таки нет...

**Comment by Leerv474** [comment]
Загоняют меня в угол ваши вопросы, думал идея четко в голове сидела, но много чего упустил в итоге.

**Comment by Leerv474** [comment]
Изменения описания
> В досках по умолчанию присутствуют 5 статус-таблиц: Проекты, Отложенные задачи, Текущие задачи, Ожидание, Выполнено. При этом можно добавить дополнительные _статус-таблицы_ под нужды пользователя. Дополнительные _статус-таблицы_ воспринимаются как стадии выполнения задач и не могут служить изначальным статусом.
Отдельно от досок существует _Корзина_ - список выгруженных задач.

> В окне распределения присутствуют кнопки выбора _статус-таблицы_ и  _доски_.

> Расширенный вид задач содержит:

> - функции редактирования атрибутов;
> - кнопку удаления;
> - кнопку преобразования в проект;
> - кнопка перемещения на другую доску.

> Функция поделиться просмотром:
Пользователи, не являющиеся владельцами доски, могут просматривать ее содержание без возможности редактирования.
В настройках доски присутсвует функция добавления пользователей на просмотр по _имени пользователя_.
У приглашенного пользователя, принявшего приглашение, гостевая доска появляется в общем списке досок.

**Comment by wldmr-key** [comment]
в общем, выглядит логично. Надеюсь, перечисленные функции обратимы?

**Comment by Leerv474** [comment]
Да, все функции обратимы. Так же я добавил описание подтверждения удаления доски.
> Удаление доски:
> Удаление требует потверждения действия посредством ввода названия доски в поле подтверждения.

Удаление остальных элементов происходит просто по нажатию кнопки, но для досок будет такое же удаление, как на гитхабе удаление репозитория.
