### ISSUE TITLE
Техническое задание

### ISSUE THREAD

**Issue by Leerv474** [Leerv474/PeachNote#6]
# Техническое задание

# 1. Общие сведения:

1. Название проекта: Система заметок GTD.
2. Наименование организации-заказчика, разработчика системы Заказчик: КФ МГТУ им. Н.Э. Баумана Разработчик: Студент КФ МГТУ им. Н.Э. Баумана группы ИУК5-52Б Ли Р. В.
3. Плановые сроки начала и окончания работы по созданию системы: Плановый срок начала работ - 5 сентября 2024 года Плановый срок окончания работ - 1 декабря 2024 года

# 2. Назначение и цели создание веб-приложения:

1. Веб-приложение разработано для предоставления сервиса учета выполнения и структуризации проектных задач пользователей.
2. Цель создания системы:
Создание системы бизнес сервиса.

# 3. Требования к системе

1. Интерфейс приложения должен быть не перегруженным и легким в навигации.
2. Система должна выполнять следующие функции:
   - регистрация и авторизация на сайте;
   - создание задач, проектов, статус-досок и таблиц;
   - редактирование задач, проектов, статус-досок и таблиц;
   - преобразование задач в проекты;
   - изменение статуса задач и проектов;
   - настройки изменения языка и внешнего вида сайта;
   - уведомления о сроках выполнения задач;
   - редактирование профиля пользователя.
3. Виды обеспечения
   - Средством описания предметной области является русский язык. Средством взаимодействия пользователя с веб-приложением являются русский и английский языки.
   - Хранение данных реализовано на основе PostgreSQL.
   - Клиентская часть реализована с помощью JavaScript, TypeScript, html и css.
   - Серверная часть реализована с помощью Java.

# 4. Состав и содержание работ по созданию системы

1. Утверждение темы, задания на разработку, технического задания. Оформление ТЗ. Описание предметной области и требований к системе. Концептуальная схема. Прототип или скетчи интерфейса.
2. Оформление введения и исследовательской части. Обоснование выбора БД, логическая схема БД, физическая схема данных. Демонстрация работы макета системы с БД.
3. Оформление проектно-конструкторской части. Демонстрация работающего веб-сайта. Презентация. Тестирование и отладка веб-сайта. Разработка эксплуатационной документации.
4. Завершающее оформление документации согласно требованиям ГОСТ. Все ошибки и проблемы устранены. Подготовка доклада. Защита курсовой работы.

# 5. Порядок контроля и приёмки веб-сайта

Веб-сайт разрабатывается с применением тестирования работоспособности функционала. При добавлении новых функций предыдущие тесты должны сохранять работоспособность. Приемка работы осуществляется комиссией КФ МГТУ им. Н.Э. Баумана кафедры ИУК5

# 6. Требования к документированию

Требуется продоставить:
а) Техническое задание в соответсвии с ГОСТ 34.602-89
b) Расчетно-пояснительную записку, включающую в исследовательскую часть, проектно-конструкторскую часть и проектно-технологическую часть, включающую в себя руководство пользователя и руководство программиста (администратора). Расчетно-пояснительная записка выполняется с учетом требований, предусмотренных ГОСТ 7.32-2001 и 2.105-95

**Comment by wldmr-key** [comment]
есть пара проблем

1. посмотри [Курсовая работа (типичные ошибки)](https://docs.google.com/document/d/1Bk74z6pNfEVUFphCJUNAe8zLYVi1B2c2rtiY6aNR_GE/edit?usp=sharing) - на то они и типовые, что ты их тоже совершаешь. Нужно исправить

2. Уже застолблена очень похожая тема. Если хочешь оставаться на выбранном пути - сделай так, чтобы функционально задания максимально различались

ниже - цитата

Техническое задание

Общие сведения

1.1.1 Название проекта: TaskFlow - совместная платформа

1.1.2 Наименование организации-заказчика, разработчика системы Заказчик: КФ МГТУ им. Н.Э. Баумана Разработчик: Студент КФ МГТУ им. Н.Э. Баумана группы ИУК5-52Б Крючков Д.А.

1.1.3 Плановые сроки начала и окончания работы по созданию системы: Плановый срок начала работ - 5 сентября 2024 года Плановый срок окончания работ - 1 декабря 2024 года

1.2 Назначение и цели создания веб-сайта

1.2.1 Система (веб-сайт) TaskFlow разработана для пользователей(компаний), которые хотят повысить свою продуктивность и структурировать задания в процессе работы как в одиночку, так и в команде. Это могут быть как отдельные пользователи, так и команды в организациях, которые хотят эффективно планировать и управлять проектами, задачами и информацией.В результате, пользователи TaskFlow смогут достичь большей продуктивности, структурированности и эффективности в своей работе, что, в свою очередь, приведет к увеличению прибыли и конкурентоспособности организации.

1.2.2 Цели создания веб-сайта:

Повышение продуктивности работы пользователей за счет эффективного планирования и организации задач и проектов.
Структурирование знаний и информации с помощью инструментов для создания баз знаний, заметок, использования тегов и меток для классификации.
Эффективное сотрудничество и общение в команде посредством совместной работы над проектами и задачами, с использованием чатов и уведомлений.
Гибкость и интуитивно понятный интерфейс для адаптации под индивидуальные потребности и рабочие процессы пользователей.
1.2.3 Объект автоматизации

Процесс управления задачами и проектами в команде или индивидуально, с использованием веб-приложения TaskFlow. В настоящее время этот процесс может осуществляться с помощью различных инструментов и методов, но они могут быть неэффективными, трудоемкими и непростыми в управлении, особенно когда дело доходит до сотрудничества в команде и отслеживания прогресса.

1.3.1 Требования к системе в целом
1.3.1.1 Требования к эргономике и технической эстетике Интерфейс веб-сайта TaskFlow должен быть интуитивно понятным, не перегруженным и не вводить пользователя в заблуждение. Все элементы интерфейса должны соответствовать их функционалу и пояснению.

1.3.2 Требования к функциям (задачам), выполняемых веб-сайтом:

Организационные инструменты:
Создание и организация рабочих пространств (воркспейсов)
Создание и управление проектами, задачами и подзадачами
Установка сроков и напоминаний для задач
Инструменты для структурирования знаний:
Создание и организация баз заданий и заметок
Использование тегов и меток для классификации информации
Инструменты для сотрудничества и общения:
Совместная работа над проектами и задачами в режиме реального времени
Комментарии и обсуждения(чаты) внутри рабочих пространств
Уведомления и оповещения о действиях других пользователей
Гибкий и настраиваемый интерфейс:
Персонализация рабочего пространства под индивидуальные потребности
1.3.3 Требования к видам обеспечения
1.3.3.1 Требования к лингвистическому обеспечению веб-сайта Средством описания предметной области, так же, как и средством взаимодействия пользователя с веб-сайтом является русский язык

1.3.3.2 Требования к входным и выходным данным

Входные данные: Пользовательские запросы и команды (создание, редактирование, удаление проектов, задач, страниц и т.д.), данные из базы данных
Выходные данные: Информация о созданных, отредактированных или удаленных объектах, уведомления о действиях других пользователей, отображаемый контент страниц

1.4 Состав и содержание работ по созданию (развитию) веб-сайта
Утверждение темы, задания на разработку, технического задания. Оформление ТЗ. Описание предметной области и требований к системе. Концептуальная схема. Прототип или скетчи интерфейса.
Оформление введения и исследовательской части. Обоснование выбора БД, логическая схема БД, физическая схема данных. Демонстрация работы макета системы с БД.
Оформление проектно-конструкторской части. Демонстрация работающего веб-сайта. Презентация. Тестирование и отладка веб-сайта. Разработка эксплуатационной документации.
Завершающее оформление документации согласно требованиям ГОСТ. Все ошибки и проблемы устранены. Подготовка доклада. Защита курсовой работы.
Порядок контроля и приёмки веб-сайта
Веб-сайт разрабатывается с применением тестирования работоспособности функционала. При добавлении новых функций предыдущие тесты должны сохранять работоспособность. Приемка работы осуществляется комиссией КФ МГТУ им. Н.Э. Баумана кафедры ИУК5
Требования к документированию
Требуется продоставить:
а) Техническое задание в соответсвии с ГОСТ 34.602-89
b) Расчетно-пояснительную записку, включающую в исследовательскую часть, проектно-конструкторскую часть и проектно-технологическую часть, включающую в себя руководство пользователя и руководство программиста (администратора). Расчетно-пояснительная записка выполняется с учетом требований, предусмотренных ГОСТ 7.32-2001 и 2.105-95

**Comment by Leerv474** [comment]
Понятно... буду думать, что теперь делать с темой.

**Comment by wldmr-key** [comment]
Так, нормально- у тебя есть хорошая отбивка - методология, которой нет у оппонента. так и делай на нее упор (в ТЗ - тоже). И будет тебе щастье!

**Comment by Leerv474** [comment]
Ну, как я понимаю, у оппонента идея сделать сайт для командных проектов. А у меня больше ежедневник (по крайней мере у меня в голове). Только вот я с этим оппонентом связался и даже интерфейс ну очень похож получается.

**Comment by wldmr-key** [comment]
ну уж, кнопки перекрасить - дело нехитрое. На мой взгляд (благодаря твоему описанию) проекты сильно разные

**Comment by Leerv474** [comment]
поправил цель, добавил объект автоматизации и изменил требования

**Comment by wldmr-key** [comment]
и еще чуть поправь по итогам консультации... И, да, для курсового проекта название должно быть чуть более информативное с небольшим включением русского языка ))

**Comment by Leerv474** [comment]
красиво написал, что хочу вбухать это кому-то за деньги

**Comment by wldmr-key** [comment]
еще раз `для курсового проекта название должно быть чуть более информативное с небольшим включением русского языка ))`

`красиво написал, что хочу вбухать это кому-то за деньги` - слишком многословно. Не нужно объяснений - создание интернет-бизнеса. Все! можно даже без интернет, чтобы более по-русски (да, хорошее русское слово "бизнес" )))

**Comment by Leerv474** [comment]
Название проекта: Система заметок GTD.

    Веб-приложение разработано для предоставления сервиса учета выполнения и структуризации проектных задач пользователей.
    Цель создания системы:
    Создание системы бизнес сервиса.

**Comment by JSwhiz** [comment]
## Исправленное техническое задание

### Общие сведения

**1.1.1 Название проекта:** TaskFlow - совместная платформа

**1.1.2 Наименование организации-заказчика, разработчика системы**  
Заказчик: КФ МГТУ им. Н.Э. Баумана  
Разработчик: Студент КФ МГТУ им. Н.Э. Баумана группы ИУК5-52Б Крючков Д.А.

**1.1.3 Плановые сроки начала и окончания работы по созданию системы:**  
Плановый срок начала работ - 5 сентября 2024 года  
Плановый срок окончания работ - 1 декабря 2024 года

### Назначение и цели создания веб-сайта

**1.2.1 Назначение:**  
TaskFlow разработано для организаций, отдельных групп пользователей, которые хотят повысить свою продуктивность и структурировать задания в процессе работы как в одиночку, так и в команде.

**1.2.2 Цели создания веб-сайта:**

* **Создание бизнеса по предоставлению сервиса:**  Система предназначена для предоставления платного сервиса структуризации знаний пользователей и повышения продуктивности групповых проектов.

**1.2.3 Объект автоматизации:**

* **Комплексный набор процессов и операций, связанных с управлением проектами, планированием, распределением ресурсов, отслеживанием прогресса и коммуникацией внутри команды с помощью чатов.**  Эти процессы могут быть автоматизированы для повышения эффективности, точности и скорости выполнения рабочих задач.

### Требования к системе в целом

**1.3.1 Требования к эргономике и технической эстетике:**

* Интерфейс приложения должен передавать наглядно представление прогресса и состояние процессов.

**1.3.2 Требования к функциям (задачам), выполняемых веб-сайтом:**

* **Авторизация на сайте:** Регистрация предусмотрена следующим образом - аккаунты заводятся под пользователей админом с предоставлением прав доступа к конкретным отделам и настройкой прав доступа согласно занимаемым должностям и допускам.
* **Создание и редактирование задач, проектов.**
* **Отслеживание статуса и сроков выполнения проектов.**
* **Изменение статуса и сроков выполнения проектов.**
* **Добавление стикеров, отвечающих за приоритет, сроки, исполнителя конкретных задач.**
* **Чаты для коммуникации между всеми сотрудниками организации.**
* **Фиксация авторов изменений в командных задачах.**

**1.3.3 Требования к видам обеспечения:**

**1.3.3.1 Виды обеспечения:**

* **Средство взаимодействия пользователя с веб-приложением:** Русский язык.
* **Хранение данных:** PostgreSQL.
* **Клиентская часть:** JavaScript (и его библиотеки/frameworks, такие как React, Angular, Vue.js), TypeScript, HTML и CSS (SASS).
* **Серверная часть:** Node.js (JS).

**1.3.3.2 Требования к входным и выходным данным:**

* **Входные данные:** Пользовательские запросы и команды (создание, редактирование, удаление проектов, задач, страниц и т.д.), данные из базы данных.
* **Выходные данные:** Информация о созданных, отредактированных или удаленных объектах, уведомления о действиях других пользователей, отображаемый контент страниц.

### Состав и содержание работ по созданию (развитию) веб-сайта

* **Утверждение темы, задания на разработку, технического задания. Оформление ТЗ.**
* **Описание предметной области и требований к системе.**
* **Концептуальная схема.**
* **Прототип или скетчи интерфейса.**
* **Оформление введения и исследовательской части.**
* **Обоснование выбора БД, логическая схема БД, физическая схема данных.**
* **Демонстрация работы макета системы с БД.**
* **Оформление проектно-конструкторской части.**
* **Демонстрация работающего веб-сайта.**
* **Презентация.**
* **Тестирование и отладка веб-сайта.**
* **Разработка эксплуатационной документации.**
* **Завершающее оформление документации согласно требованиям ГОСТ.**
* **Все ошибки и проблемы устранены.**
* **Подготовка доклада.**
* **Защита курсовой работы.**

### Порядок контроля и приёмки веб-сайта

* Веб-сайт разрабатывается с применением тестирования работоспособности функционала.
* При добавлении новых функций предыдущие тесты должны сохранять работоспособность.
* Приемка работы осуществляется комиссией КФ МГТУ им. Н.Э. Баумана кафедры ИУК5.

### Требования к документированию

* **Техническое задание в соответствии с ГОСТ 34.602-89.**
* **Расчетно-пояснительная записка, включающая:**
    * **Исследовательскую часть.**
    * **Проектно-конструкторскую часть.**
    * **Проектно-технологическую часть, включающую в себя руководство пользователя и руководство программиста (администратора).**
* **Расчетно-пояснительная записка выполняется с учетом требований, предусмотренных ГОСТ 7.32-2001 и 2.105-95.**



Мой конечный вариант раздумий
