### ISSUE TITLE
Предварительный анализ аналогов

### ISSUE THREAD

**Issue by Leerv474** [Leerv474/PeachNote#7]
# Цель

Определить преимущества и недостатки аналогов разрабатываемого веб-приложения

# Список аналогов

- [Trello](https://trello.com/)
- [Todoist](https://todoist.com/)
- [Weeek](https://weeek.net/)
- [Microsoft To Do](https://to-do.office.com/tasks/)

# Основные функции и возможности

Во всех перечисленных системах присутсвуют следующие функции:

- создание задач
- синхронизация с календарем
- система приоритетов
- сортировка задач
- мобильные версии
- интеграции с другими сервисами
- уведомления
- платные микросервисы
- групповые проекты

Trello отличается простотой и отзывчивостью интерфейса, гибкостью использования и обширным набором дополнительных функций платной версии. В то же время бесплатный план крайне ограничивает возможности пользователя: отсутсвие коллабораций, органичения в количестве проектов и интергрированных сервисов. Кроме того, сервис сильно зависит от интернет соединения и ограниченную систему уведомлений.
Основные отличительные черты Trello - это фукнции автоматизации действий и Power-Ups.
Автоматизация добивается встроенным инструментов Butler, в котором можно задач ряд определенных действий, срабатывающих по триггеру.
Power-Ups - это система пользовательских дополнений, интегрируемых с систему.
![trello](https://github.com/user-attachments/assets/a0fb9fb0-26f1-4848-92fa-c4ad1d01fe1a)

Todoist имеет приятный отзывчивый интерфейс как в веб, так и в мобильной версии, а также множество полезных функций. Недостатками данной системы является то, что множество предлагаемых функций недоступны в бесплатной версии, отсутствие тайм-трекинга, и чрезмерное упрощение интерфейса.
Приложение предоставляет пользователю систему меток и фильтров. Метки используются для классификации задач по тегам, а фильтры позволяют выводить список задач по нескольким критериям: теги, дата и время, приоритет и д.р., например: "Сегодня & @работа".
![todoist](https://github.com/user-attachments/assets/fac1ebf4-4a12-4271-8ba1-b6bfdb5901d8)

Weeek предоставляет бесплатный доступ к синхронизации с календарем, уведомления через социальную сеть Telegram, обширный бесплатный план и доступный платный план.
Однако интерфейс является перегруженным и неотзывчивым как и в веб версии, так и в мобильном приложении.
Отличительными особенностями Weeek являются уведомления через социальную сеть Telegram и интеграция с популярными калернадрными сервисами.
<img width="916" alt="weeek" src="https://github.com/user-attachments/assets/0142b9a8-cbd3-4b52-9c1e-a250d85786f6">

Microsoft To Do является простым менеджером задач с обширной интеграцией в приложениях Microsoft и облачной сихронизацией, что позволяет получить доступ к данным из любого приложения или устройства и отличается от аналогов отсутсвием платной версии. В то же время, по сравнению с другими аналогами у него крайне ограниченный функционал.
![microsoft-todo](https://github.com/user-attachments/assets/4859fc6b-d04e-4535-b5d3-325f3479a54c)

# Особенность разрабатываемого веб-приложения

По сравнению с аналогами, основной особенностью разрабатываемого веб-приложения является автоматизация сортировки задач по метологии "Getting Things Done", сохраняя простые и полезные функции таких аналогов, например: таблицы, тайм-трекинг и уведомления.

**Comment by Leerv474** [comment]
Не совсем понимаю, как подытожить анализ и вообще то ли я сделал

**Comment by wldmr-key** [comment]
ты сделал вполне себе то. В РПЗ стоит добавить скриншотики и ссылки на аналоги и немного описать их отличительные особенности. Откуда ты взял у себя командные проекты - непонятно. Или они будут?

**Comment by Leerv474** [comment]
неправильно сформулировал командные проекты. я про тот момент, где можно просмотром поделиться, чтобы коллеги знали, как идет прогресс, но сейчас обдумываю,  и не сильно это прям в сторону командной функциональности, а скорее просто мелкая фича. Поправлю

**Comment by Leerv474** [comment]
добавил фичи приложений, которые действительно выделяют их среди других, и скриншоты

**Comment by wldmr-key** [comment]
норм
`Но слабой частью проекта` - это лучше не писать. Когда проект будет готов у него появятся и другие слабые части ))

**Comment by Leerv474** [comment]
поправил
