### ISSUE TITLE
Логическая и физическая схема данных. Описание целостности данных.

### ISSUE THREAD

**Issue by Leerv474** [Leerv474/PeachNote#8]
# ER-Диаграммы
## Логическая схема
![LogicalSchema](https://github.com/user-attachments/assets/5f4752e4-8164-415f-8db1-06e45775aa45)

## Физическая схема
![PhysicalSchema](https://github.com/user-attachments/assets/1ba9c043-8e39-44a1-8068-8654a02912e3)

# Описание целостности данных

_Пользователь_:

- индентификатор: тип данных - BIGINT, автоматические генерируется, ПЕРВИЧНЫЙ КЛЮЧ;
- имя пользователя: тип данных — VARCHAR(127), должен быть не нулевым и не пустым;
- пароль: тип данных — VARCHAR(255), должен быть не нулевым не пустым;
- электронная почта: тип данных — VARCHAR(16), должна быть уникальной и не пустой;
- статус активности аккаунта: тип данных - BOOLEAN, по умолчанию - true;
- статус подтверждения аккаунта: тип данных - BOOLEAN, по умолчанию - false;
- тег telegram: тип данных - VARCHAR(255).

_Доска_:

- индентификатор: тип данных - BIGINT, автоматические генерируется, ПЕРВИЧНЫЙ КЛЮЧ;
- название: тип данных — VARCHAR(127), не должно быть пустым.

  > !ПРИМЕЧАНИЕ  
  > Максимальное количество статус-таблиц в одной доске не превышает 20.

_Роль_: 

- название: тип данных - VARCHAR(127), должен быть уникальным и не пустым, ПЕРВИЧНЫЙ КЛЮЧ;
- описание: тип данных - TEXT;
- уровень доступа: тип данных - INTEGER, должен быть больше нуля и не может быть null;
- статус активности роли: тип данных - BOOLEAN, по умолчанию - true;

_Статус-таблица_:

- индентификатор: тип данных - BIGINT, автоматические генерируется, ПЕРВИЧНЫЙ КЛЮЧ;
- название: тип данных — VARCHAR(127), не должно быть пустым;
- номер этапа выполнения: тип данных — INTEGER, больше нуля и не больше 20.

_Проект_:

- индентификатор: тип данных - BIGINT, автоматические генерируется, ПЕРВИЧНЫЙ КЛЮЧ;
- название: тип данных — VARCHAR(127), не должно быть пустым;
- описание: тип данных — TEXT;
- срок: тип данных — DATE.

  > !ПРИМЕЧАНИЕ  
  > Узнать дату начала или конца выполнения проекта можно через первую созданную или последнюю выполненную задачу, принадлежащую проекту.

_Задача_:

- индентификатор: тип данных - BIGINT, автоматические генерируется, ПЕРВИЧНЫЙ КЛЮЧ;
- название: тип данных — VARCHAR(127), не должно быть пустым;
- описание: тип данных — TEXT;
- срок: тип данных — DATE;
- дата создания: тип данных — DATE, автоматически заполняется текущей датой при создании;
- дата выполнения: тип данных — DATE, автоматически заполняется текущей датой при изменении статуса на "выполнено";
- приоритет: тип данных — INTEGER, больше нуля и не больше 100.

**Comment by Leerv474** [comment]
Как уже писал в описании, решил сделать доступ пользователям. Добавил связующую таблицу. В Концептуальной схеме поменял стрелку на многие ко многим.

Вопрос: стоит ли мне вывести уровни разрешений - `permission_level` в отдельную таблицу или это уже слишком? Я вижу выгоду, потому что тогда у меня могут быть только такие то уровни доступа (редактор, зритель, и еще можно расширить) и проверка будет тогда внутри базы данных. Вроде есть польза, а вроде и без этого хорошо.

**Comment by wldmr-key** [comment]
такие штуки, как разрешения, как правило, достаточно жесткие, так как они глубоко прошиты в логику приложения и интерфейсы. Поэтому, если их изначально немного, то их хардкодят. Если потенциально возможно расширение, то да, отправляют справочником в БД. Оценивай!

по целостности - может ли задача, принадлежащая проекту, относится к одной статус-таблице, а проект к другой?

**Comment by Leerv474** [comment]
проект содержится в списке проектов, его задачи выгружаются в основные статус таблицы. Если все задачи проекта закончены, то сам проект переносится в выполнено, а его задачи скрываются, чтобы не заполонять список уже не первостепенной информацией.

Первый приоритет трекинга задач  - это односложные задачи. Проекты существуют для группировки задач, ведущих к какому-то частному результату. Статус таблицы существуют, чтобы группировать задачи по собственно статуса выполнения

**Comment by wldmr-key** [comment]
а прямой ответ на вопрос дать не? ))

**Comment by Leerv474** [comment]
да, может

**Comment by Leerv474** [comment]
поменял логическую схему. решил все таки добавить роли для расширяемости проекта в целом (это же поддерживается со стороны проектирования приложений, верно?) теперь новая таблица содержит все роли, содержит числовое значение уровня доступа, описание (для четкого описания возможностей роли) и `access_status`, для случаев, когда необходимо отключить роль на некоторое время.

**Comment by Leerv474** [comment]
добавил роли в физическую схему и описание.
изменил пользователя: теперь у пользователя все таки есть id и почта. Логин поменял на просто имя пользователя, которое можно будет редактировать
